# Code to analyze data type and values for Wikidata properties

Report:

There are 17 dataypes.

`wikibase-item` and `external-id` are for properties that have entity values 


[('external-id', 5883),
 ('wikibase-item', 1329),
 ('quantity', 537),
 ('string', 278),
 ('url', 72),
 ~~('commonsMedia', 62),~~
 ('monolingualtext', 47),
 ('time', 46),
 ~~('math', 19),~~
 ~~('wikibase-property', 15),~~
 ~~('wikibase-sense', 13),~~
 ~~('wikibase-lexeme', 12),~~
 ~~('globe-coordinate', 9),~~
 ~~('musical-notation', 6),~~
 ~~('tabular-data', 5),~~
 ('wikibase-form', 5),
 ~~('geo-shape', 2)]~~

ignored: 

**Property datatypes that needs transformation**
- quantity
- time


**Property datatypes that don't need transformation**
- string
- url
- monolingualtext
- wikibase-form

In [1]:
import json
import pandas as pd
from pathlib import Path 

# 17 categories found in the documentation
datatypes = ["time", "url", "string", "globe-coordinate", "external-id", "wikibase-form", "geo-shape", "wikibase-item", "wikibase-lexeme", "commonseMedia", "monolingualtext", "musical-notation", "math", "wikibase-property", "quantity", "wikibase-sense", "tabular-data"]
data_path = "/afs/crc.nd.edu/group/dmsquare/vol1/data/WIKIPEDIA/wikidata_tmp/property_labels/0.tsv"

df = pd.read_csv(data_path, sep='\t', header=0)
df.head()

        datatype                      label   pid
0  wikibase-item             place of birth   P19
1  wikibase-item                     father   P22
2  wikibase-item              position held   P39
3  wikibase-item            commissioned by   P88
4  wikibase-item  member of political party  P102

In [2]:
from collections import Counter
cnt = Counter(list(df["datatype"]))
print(len(cnt), "datatypes found in data")
cnt.most_common()

17 datatypes found in data

[('external-id', 5883),
 ('wikibase-item', 1329),
 ('quantity', 537),
 ('string', 278),
 ('url', 72),
 ('commonsMedia', 62),
 ('monolingualtext', 47),
 ('time', 46),
 ('math', 19),
 ('wikibase-property', 15),
 ('wikibase-sense', 13),
 ('wikibase-lexeme', 12),
 ('globe-coordinate', 9),
 ('musical-notation', 6),
 ('tabular-data', 5),
 ('wikibase-form', 5),
 ('geo-shape', 2)]

In [3]:
statement_path = "/afs/crc.nd.edu/group/dmsquare/vol2/myu2/ComparisonSentences/data/wikidata_processed/entity_values/0.tsv"
table = pd.read_csv(statement_path, header=0, sep='\t')
table.head()

  property_id    qid                  value
0        P569    Q24  +1966-02-18T00:00:00Z
1       P1448    Q24             Jack Bauer
2        P373     Q8              Happiness
3       P2572     Q8                  happy
4        P373  Q1868             Paul Otlet

In [4]:
def show_label(pid):
    return list(df.loc[df["pid"]==pid]["label"])

In [5]:
def peek_datatype(datatype):
    pid_list = list(df.loc[df["datatype"] == datatype]["pid"])
    print(f"{len(pid_list)} pid found for type {datatype}")
    return table.loc[table["property_id"].isin(pid_list)]

In [6]:
peek_datatype("external-id")

5883 pid found for type external-id

Empty DataFrame
Columns: [property_id, qid, value]
Index: []

In [7]:
peek_datatype("wikibase-item")

1329 pid found for type wikibase-item

Empty DataFrame
Columns: [property_id, qid, value]
Index: []

In [8]:
peek_datatype("string")

278 pid found for type string

        property_id        qid                value
2              P373         Q8            Happiness
3             P2572         Q8                happy
4              P373      Q1868           Paul Otlet
7             P1472      Q1868           Paul Otlet
8              P373        Q23    George Washington
...             ...        ...                  ...
2564319        P281  Q16470052               654231
2564330        P281  Q16470244               654222
2564333        P281  Q16470272               654201
2564341        P373  Q16470336           Purviškiai
2564345        P373  Q16470415  Pypliai (Širvintos)

[819805 rows x 3 columns]

In [9]:
peek_datatype("url")

72 pid found for type url

        property_id        qid                                    value
25             P856        Q42                https://douglasadams.com/
31            P1401      Q2013        https://phabricator.wikimedia.org
32            P1401      Q2013           https://bugzilla.wikimedia.org
33             P856      Q2013                https://www.wikidata.org/
37            P1482      Q2013  https://stackoverflow.com/tags/wikidata
...             ...        ...                                      ...
2564096        P856  Q16467122           http://www.sonjaschwedersky.nl
2564102        P856  Q16467170          http://www.primariatiganasi.ro/
2564110        P856  Q16467532       http://helsingborgsbryggeri.se/en/
2564146        P856  Q16467833                       http://www.nvi.lt/
2564300        P856  Q16469850                    https://murom-eks.com

[131659 rows x 3 columns]

In [10]:
peek_datatype("commonsMedia")

62 pid found for type commonsMedia

Empty DataFrame
Columns: [property_id, qid, value]
Index: []

In [11]:
peek_datatype("monolingualtext")

47 pid found for type monolingualtext

,property_id,qid,value
1,P1448,Q24,Jack Bauer
19,P1449,Q23,American Fabius
29,P1813,Q42,Douglas Adams
58,P1705,Q2013,Wikidata
112,P1448,Q328,English Wikipedia
...,...,...,...
2561119,P1476,Q16425108,More folksongs from Iceland
2563166,P1476,Q16448724,Himalayan Districts of the North-western Provi...
2563995,P1476,Q16466026,My Own Kind of Freedom
2564044,P1476,Q16466460,…And Then You Shoot Your Cousin
2564099,P1476,Q16467342,Impulse Control

In [12]:
timestamps = list(peek_datatype("time")[:100]["value"])

46 pid found for type time

In [14]:
import 
timestamps[0]

'+1966-02-18T00:00:00Z'

In [29]:
import datetime
def get_time(dt_str):
    dt = datetime.datetime.strptime(dt_str, "+%Y-%m-%dT%H:%M:%S")
    return dt

In [30]:
gt(timestamps[0][:-1])

datetime.datetime(1966, 2, 18, 0, 0)

In [32]:
list(peek_datatype("quantity")["value"])

537 pid found for type quantity

['+0',
 '+1',
 '+74',
 '+193',
 '+1.96',
 '+10',
 '+2565510',
 '+4498339',
 '+12325',
 '+12382',
 '+9525',
 '+14946',
 '+7755',
 '+8206',
 '+7248',
 '+7136',
 '+20806',
 '+1100',
 '+4400',
 '+14000000',
 '+14200000',
 '+17.5',
 '+10.5',
 '+24797289',
 '+115603',
 '+27239475',
 '+31331313',
 '+6343474',
 '+5005658',
 '+4017334',
 '+3005288',
 '+2040371',
 '+1006271',
 '+103373',
 '+12252',
 '+545507',
 '+11150516',
 '+11099554',
 '+11035948',
 '+10951266',
 '+10839905',
 '+10753080',
 '+10666866',
 '+10584534',
 '+10511382',
 '+10445852',
 '+10396421',
 '+10355844',
 '+10309725',
 '+10263414',
 '+9153489',
 '+9183948',
 '+9220578',
 '+9289770',
 '+9378113',
 '+9463667',
 '+9527807',
 '+9580991',
 '+9618756',
 '+9646032',
 '+9655549',
 '+9673162',
 '+9711115',
 '+9741720',
 '+9772419',
 '+9800700',
 '+9818227',
 '+9830358',
 '+9839534',
 '+9848382',
 '+9859242',
 '+9858982',
 '+9856303',
 '+9855520',
 '+9855372',
 '+9858308',
 '+9861823',
 '+9870234',
 '+9901664',
 '+9937697',
 '+9967379',
 '+10004486',
 '+10045158',
 '+10084475',
 '+10115603',
 '+10136811',
 '+10156637',
 '+10181245',
 '+10203008',
 '+10226419',
 '+10251250',
 '+10286570',
 '+10332785',
 '+10376133',
 '+10421137',
 '+10478617',
 '+10547958',
 '+10625700',
 '+10709973',
 '+10796493',
 '+10920272',
 '+11047744',
 '+11128246',
 '+11182817',
 '+11372068',
 '+11431406',
 '+11492641',
 '+11431406',
 '+11376070',
 '+11322088',
 '+11267910',
 '+11209044',
 '+11150516',
 '+11099554',
 '+11035948',
 '+10951266',
 '+10839905',
 '+10753080',
 '+10665140',
 '+10584534',
 '+10511382',
 '+10445852',
 '+10396421',
 '+10355844',
 '+10309725',
 '+10263414',
 '+10239085',
 '+10213752',
 '+10192264',
 '+10170226',
 '+10142776',
 '+10130398',
 '+10100341',
 '+10068319',
 '+10021997',
 '+9978681',
 '+9848647',
 '+9650944',
 '+9189737',
 '+8512185',
 '+8091997',
 '+7405570',
 '+7423784',
 '+6693546',
 '+6069317',
 '+5520016',
 '+4827834',
 '+4529465',
 '+4337198',
 '+3786556',
 '+31112',
 '+8330',
 '+11357',
 '+12063',
 '+95560',
 '+97774',
 '+18',
 '+1.62',
 '+1.67',
 '+1.67',
 '+1.65',
 '+1.67',
 '+1.72',
 '+1.76',
 '+1.8',
 '+1.82',
 '+1.85',
 '+1.84',
 '+1.86',
 '+1.81',
 '+1.79',
 '+1.75',
 '+1.75',
 '+65',
 '+66',
 '+67',
 '+18',
 '+18',
 '+0.755',
 '+0.774',
 '+0.806',
 '+0.851',
 '+0.874',
 '+0.866',
 '+0.883',
 '+0.886',
 '+0.889',
 '+0.888',
 '+0.890',
 '+0.810',
 '+0.825',
 '+0.839',
 '+0.845',
 '+0.852',
 '+0.857',
 '+0.862',
 '+0.866',
 '+0.868',
 '+0.873',
 '+0.876',
 '+0.879',
 '+0.882',
 '+0.885',
 '+0.889',
 '+0.896',
 '+0.899',
 '+0.899',
 '+0.899',
 '+0.903',
 '+0.904',
 '+0.905',
 '+0.908',
 '+0.909',
 '+0.913',
 '+0.915',
 '+0.916',
 '+8',
 '+230',
 '+77.61951',
 '+77.72195',
 '+77.97317',
 '+78.07561',
 '+78.12927',
 '+78.87805',
 '+78.98049',
 '+79.38049',
 '+79.78293',
 '+79.68049',
 '+80.03415',
 '+80.18293',
 '+80.58537',
 '+80.38537',
 '+80.5878',
 '+81.2878',
 '+80.99268',
 '+30528',
 '+0.8',
 '+44725',
 '+45005',
 '+44858',
 '+99',
 '+20.7',
 '+20.1',
 '+21.3',
 '+21.2',
 '+22.7',
 '+21',
 '+7.51',
 '+7.64',
 '+7.78',
 '+7.78',
 '+7.77',
 '+7.93',
 '+7.93',
 '+8.05',
 '+8.05',
 '+8.05',
 '+8.05',
 '+8.16',
 '+8.15',
 '+14.8',
 '+108',
 '+1.65',
 '+188',
 '+126',
 '+2.5',
 '+27',
 '+95',
 '+115',
 '+80',
 '+67',
 '+45000',
 '+1375198619',
 '+1332810869',
 '+1397028553',
 '+1403500365',
 '+1390110388',
 '+1359755102',
 '+1409517397',
 '+1367480264',
 '+1382793212',
 '+1442965000',
 '+1443497378',
 '+5',
 '+220',
 '+18',
 '+9596961',
 '+0.430',
 '+0.467',
 '+0.501',
 '+0.545',
 '+0.588',
 '+0.641',
 '+0.699',
 '+0.707',
 '+0.718',
 '+0.723',
 '+0.728',
 '+0.502',
 '+0.510',
 '+0.521',
 '+0.531',
 '+0.541',
 '+0.550',
 '+0.559',
 '+0.568',
 '+0.576',
 '+0.585',
 '+0.594',
 '+0.602',
 '+0.611',
 '+0.623',
 '+0.635',
 '+0.647',
 '+0.661',
 '+0.675',
 '+0.685',
 '+0.694',
 '+0.706',
 '+0.714',
 '+0.722',
 '+0.729',
 '+0.738',
 '+0.743',
 '+0.748',
 '+0.752',
 '+1.453',
 '+1.447',
 '+1.455',
 '+1.469',
 '+1.486',
 '+1.502',
 '+1.513',
 '+1.521',
 '+1.526',
 '+1.531',
 '+1.535',
 '+1.539',
 '+1.544',
 '+1.549',
 '+1.555',
 '+1.562',
 '+1.60',
 '+71.521',
 '+71.955',
 '+72.401',
 '+72.84',
 '+73.257',
 '+73.642',
 '+73.987',
 '+74.291',
 '+74.562',
 '+74.808',
 '+75.032',
 '+75.236',
 '+75.425',
 '+75.602',
 '+75.769',
 '+75.932',
 '+76.092',
 '+76.252',
 '+9.7',
 '+9.6',
 '+10.9',
 '+11.7',
 '+13.2',
 '+2.8',
 '-58',
 '+13',
 '+4.42',
 '+4.7',
 '+4.79',
 '+4.94',
 '+5.01',
 '+4.95',
 '+5.02',
 '+5.04',
 '+4.49',
 '+4.86',
 '+5',
 '+5.04',
 '+4.92',
 '+4.73',
 '+4.79',
 '+4.71',
 '+2.27',
 '+5234700',
 '+23903',
 '+272490',
 '+270659',
 '+241916',
 '+250138',
 '+294610',
 '+292000',
 '+270000',
 '+330000',
 '+331000',
 '+351360',
 '+301258',
 '+333835',
 '+334459',
 '+351361',
 '+267566',
 '+331447',
 '+332546',
 '+359774',
 '+253290',
 '+327688',
 '+255497',
 '+244275',
 '+356369',
 '+250432',
 '+291150',
 '+72673',
 '+28288',
 '+25402',
 '+1570',
 '+2',
 '+183',
 '+2',
 '+229',
 '+152',
 '+0.381',
 '+120',
 '+101.3',
 '+0',
 '+90',
 '+1.57',
 '+34.67',
 '+134803',
 '+38055',
 '+26669',
 '+41061',
 '+136252',
 '+139963',
 '+135787',
 '+136463',
 '+128120',
 '+140686',
 '+132209',
 '+129509',
 '+132820',
 '+136942',
 '+134633',
 '+76',
 '+62762',
 '+73025',
 '+16676',
 '+11351',
 '+2690',
 '+209860',
 '+211373',
 '+213454',
 '+215366',
 '+222104',
 '+216815',
 '+217728',
 '+180943',
 '+198305',
 '+194656',
 '+197536',
 '+206229',
 '+209613',
 '+208033',
 '+50.39',
 '+74',
 '+102826',
 '+113989',
 '+75580',
 '+74657',
 '+10347892',
 '+8929316',
 '+8993985',
 '+9030355',
 '+9035365',
 '+8998595',
 '+8930990',
 '+8874520',
 '+8836650',
 '+8757705',
 '+8680431',
 '+8643756',
 '+8630430',
 '+8633100',
 '+8754365',
 '+9093470',
 '+9355810',
 '+9455675',
 '+9558250',
 '+9661265',
 '+9766312',
 '+9851362',
 '+9911771',
 '+9957865',
 '+9996232',
 '+10023613',
 '+10032734',
 '+10030031',
 '+10019610',
 '+10005000',
 '+9983218',
 '+9960235',
 '+9952494',
 '+9964675',
 '+9991525',
 '+10026176',
 '+10063945',
 '+10108977',
 '+10160196',
 '+10217828',
 '+10289898',
 '+10362722',
 '+10419631',
 '+10458821',
 '+10483861',
 '+10503330',
 '+10522288',
 '+10542964',
 '+10558177',
 '+10568247',
 '+10573100',
 '+10557560',
 '+10514844',
 '+10457295',
 '+10600000',
 '+17103400',
 '+8857716',
 '+14',
 '+230',
 '+18',
 '+18',
 '+18',
 '+92212',
 '+0.645',
 '+0.676',
 '+0.710',
 '+0.759',
 '+0.782',
 '+0.792',
 '+0.819',
 '+0.825',
 '+0.827',
 '+0.828',
 '+0.830',
 '+0.711',
 '+0.720',
 '+0.732',
 '+0.745',
 '+0.753',
 '+0.760',
 '+0.767',
 '+0.773',
 '+0.780',
 '+0.779',
 '+0.785',
 '+0.790',
 '+0.792',
 '+0.796',
 '+0.797',
 '+0.800',
 '+0.803',
 '+0.810',
 '+0.814',
 '+0.817',
 '+0.822',
 '+0.826',
 '+0.829',
 '+0.837',
 '+0.839',
 '+0.842',
 '+0.845',
 '+0.847',
 '+66',
 '+15044',
 '+18704',
 '+19620',
 '+68261',
 '+71685',
 '+79526',
 '+86962',
 '+88296',
 '+88529',
 '+102270',
 '+1.5',
 '+1.55',
 '+1.45',
 '+1.46',
 '+1.44',
 '+1.4',
 '+1.41',
 '+1.37',
 '+1.35',
 '+1.39',
 '+1.34',
 '+1.39',
 '+1.35',
 '+1.28',
 '+1.21',
 '+1.21',
 '+75.96341',
 '+76.31463',
 '+76.81463',
 '+77.06585',
 '+77.21951',
 '+77.67073',
 '+78.07073',
 '+78.41951',
 '+78.32195',
 '+78.52439',
 '+78.72683',
 '+79.02683',
 '+80.47073',
 '+80.37317',
 '+80.72195',
 '+81.12195',
 '+81.12439',
 '+81.12683',
 '+23',
 '+7.90',
 '+19',
 '+7',
 '+18',
 '+0.915',
 '+0.801',
 '+0.830',
 '+0.855',
 '+0.887',
 '+0.906',
 '+0.911',
 '+0.915',
 '+0.916',
 '+0.926',
 '+0.809',
 '+0.814',
 '+0.824',
 '+0.829',
 '+0.834',
 '+0.839',
 '+0.844',
 '+0.850',
 '+0.855',
 '+0.868',
 '+0.877',
 '+0.883',
 '+0.889',
 '+0.897',
 '+0.903',
 '+0.911',
 '+0.915',
 '+0.917',
 '+0.917',
 '+0.921',
 '+0.926',
 '+0.928',
 '+0.928',
 '+0.930',
 '+0.933',
 '+0.934',
 '+0.936',
 '+65.25',
 '+5',
 '+100',
 '+50',
 '+2.3',
 '+80500000',
 '+81752000',
 '+82002000',
 '+82315000',
 '+82501000',
 '+82537000',
 '+82260000',
 '+82037000',
 '+82012000',
 '+81539000',
 '+80975000',
 '+79753000',
 '+78390000',
 '+77780000',
 '+77709000',
 '+78248000',
 '+78397000',
 '+78073000',
 '+78209000',
 '+78882000',
 '+78821000',
 '+78069000',
 '+77550000',
 '+76864000',
 '+75591000',
 '+74383000',
 '+73147000',
 '+72031000',
 '+70943000',
 '+70945000',
 '+81083600',
 '+81292400',
 '+82175700',
 '+82521653',
 '+82695000',
 '+82979100',
 '+83149300',
 '+18',
 '+1.36',
 '+1.38',
 '+1.35',
 '+1.34',
 '+1.34',
 '+1.36',
 '+1.34',
 '+1.33',
 '+1.37',
 '+1.38',
 '+1.36',
 '+1.39',
 '+1.36',
 '+1.38',
 '+1.39',
 '+1.39',
 '+357587.77',
 '+230',
 '+80.8',
 '+78.5',
 '+83.3',
 '+77.72683',
 '+77.92683',
 '+78.32927',
 '+78.22927',
 '+78.38049',
 '+78.68049',
 '+78.93171',
 '+79.13171',
 '+79.53415',
 '+79.73659',
 '+79.83659',
 '+79.9878',
 '+80.43659',
 '+80.53902',
 '+80.49024',
 '+81.09024',
 '+80.64146',
 '+33333',
 '+42.6',
 '+41.2',
 '+9.19',
 '+9.35',
 '+12.6',
 '+99',
 '-45.9',
 '+8.67',
 '+8.68',
 '+8.68',
 '+8.61',
 '+8.63',
 '+8.64',
 '+8.64',
 '+8.31',
 '+8.34',
 '+8.34',
 '+8.38',
 '+8.82',
 '+8.82',
 '+14.8',
 '+7649026',
 '+7845746',
 '+8047690',
 '+8251999',
 '+8455039',
 '+8654071',
 '+8847757',
 '+9036236',
 '+9220119',
 '+9400705',
 '+9578923',
 '+9755352',
 '+9929560',
 '+10100403',
 '+10266278',
 '+10426432',
 '+10580399',
 '+10729757',
 '+10878343',
 '+11031280',
 '+11192384',
 '+11363219',
 '+11543263',
 '+11731654',
 '+11926647',
 '+12126956',
 '+12331704',
 '+12541298',
 '+12757095',
 '+12981032',
 '+13213930',
 '+13456476',
 '+13706485',
 '+13958378',
 '+14204726',
 '+14440103',
 '+14662323',
 '+14872458',
 '+15072409',
 '+15265536',
 '+15454402',
 '+15639289',
 '+15819522',
 '+15995658',
 '+16168241',
 '+16337749',
 '+16504530',
 '+16668892',
 '+16831184',
 '+16991729',
 '+17150760',
 '+17308449',
 '+17464814',
 '+17619708',
 '+17373831',
 '+18054726',
 '+19458000',
 '+88621',
 '+103948',
 '+142376',
 '+167350',
 '+168115',
 '+175074',
 '+179996',
 '+182581',
 '+205047',
 '+18',
 '+0.636',
 '+0.654',
 '+0.699',
 '+0.723',
 '+0.752',
 '+0.788',
 '+0.814',
 '+0.821',
 '+0.827',
 '+0.830',
 '+0.832',
 '+0.701',
 '+0.711',
 '+0.719',
 '+0.713',
 '+0.718',
 '+0.727',
 '+0.734',
 '+0.741',
 '+0.747',
 '+0.753',
 '+0.759',
 '+0.766',
 '+0.768',
 '+0.774',
 '+0.783',
 '+0.788',
 '+0.795',
 '+0.806',
 '+0.804',
 '+0.808',
 '+0.814',
 '+0.819',
 '+0.828',
 '+0.833',
 '+0.840',
 '+0.842',
 '+0.843',
 '+2.107',
 '+2.073',
 '+2.042',
 '+2.013',
 '+1.986',
 '+1.959',
 '+1.934',
 '+1.91',
 '+1.887',
 '+1.865',
 '+1.844',
 '+1.824',
 '+1.806',
 '+1.789',
 '+1.774',
 '+1.761',
 '+18',
 '+756102',
 '+6',
 '+220',
 '+76.533',
 '+76.793',
 '+77.034',
 '+77.255',
 '+77.453',
 '+77.632',
 '+77.791',
 '+77.934',
 '+78.066',
 '+78.193',
 '+78.32',
 '+78.454',
 '+78.599',
 '+78.758',
 '+78.931',
 '+79.117',
 '+79.315',
 '+79.522',
 '+80',
 '+10.6',
 '+10.9',
 '+12.2',
 '+10.6',
 '+10.9',
 '+19',
 '+8.85',
 '+8.99',
 '+8.87',
 '+8.82',
 '+8.77',
 '+8.86',
 '+7.51',
 '+7.55',
 '+7.38',
 '+7.22',
 '+7.26',
 '+7.33',
 '+8.28',
 '+73000000',
 '+202656788',
 '+72775883',
 '+74988037',
 '+77286629',
 '+79643017',
 '+82017016',
 '+84379369',
 '+86721875',
 '+89052356',
 '+91377490',
 '+93709914',
 '+96060361',
 '+98427874',
 '+100812672',
 '+103228641',
 '+105693434',
 '+108219657',
 '+110808302',
 '+113455308',
 '+116160978',
 '+118924135',
 '+121740438',
 '+124610790',
 '+127525420',
 '+130455659',
 '+133364277',
 '+136223043',
 '+139023394',
 '+141767626',
 '+144452622',
 '+147078659',
 '+149648341',
 '+152153539',
 '+154597985',
 '+157011131',
 '+159432909',
 '+161890816',
 '+164392423',
 '+166925457',
 '+169472347',
 '+172006362',
 '+174504898',
 '+176968205',
 '+179393768',
 '+181752951',
 '+184010283',
 '+186142403',
 '+188134315',
 '+189996976',
 '+191765567',
 '+193490922',
 '+195210154',
 '+196935134',
 '+198656019',
 '+200361925',
 '+206081432',
 '+207353391',
 '+208494900',
 '+210147125',
 '+211755692',
 '+213317639',
 '+2263423',
 '+2529220',
 '+2598407',
 '+2817364',
 '+3181989',
 '+3732292',
 '+2479618',
 '+3230205',
 '+14',
 '+2.399',
 '+2.364',
 '+2.318',
 '+2.264',
 ...]

In [2]:
import pandas as pd
df = pd.read_csv("/afs/crc.nd.edu/group/dmsquare/vol2/myu2/ComparisonSentences/data/wikidata_processed/property_labels/0_tmp.tsv", sep='\t', header=0)

pid2type = {}
for index, row in df.iterrows():
    pid2type[row["pid"]] = row["datatype"]
print(len(pid2type))

1244

In [1]:
from pathlib import Path
import json
import os
from collections import Counter
def _load_property2aliases(path):
    # from the property_aliases table
    pid2aliases = {}
    with open(path, 'r') as f:
        header = f.readline()
        assert header.strip().split('\t') == ["alias", "pid"]
        while True:
            line = f.readline()
            if len(line) == 0:
                break
            alias, pid = line.strip().split('\t')
            if pid not in pid2aliases:
                pid2aliases[pid] = []
            pid2aliases[pid].append(alias)
    return pid2aliases
path_prop_alias = Path("/afs/crc.nd.edu/group/dmsquare/vol2/myu2/ComparisonSentences/data/wikidata_processed/property_aliases/0.tsv")
pid2alias = _load_property2aliases(path_prop_alias)

In [3]:
pid2alias["P22"]

['father',
 'dad',
 'daddy',
 'has father',
 'parent',
 'is son of',
 'is daughter of',
 'is child of',
 'son of',
 'daughter of',
 'child of']